/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerticalIndexRouteImport } from './routes/$vertical/index'
import { Route as VerticalLocationSlugRouteImport } from './routes/$vertical/$locationSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerticalIndexRoute = VerticalIndexRouteImport.update({
  id: '/$vertical/',
  path: '/$vertical/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerticalLocationSlugRoute = VerticalLocationSlugRouteImport.update({
  id: '/$vertical/$locationSlug',
  path: '/$vertical/$locationSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$vertical/$locationSlug': typeof VerticalLocationSlugRoute
  '/$vertical/': typeof VerticalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$vertical/$locationSlug': typeof VerticalLocationSlugRoute
  '/$vertical': typeof VerticalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$vertical/$locationSlug': typeof VerticalLocationSlugRoute
  '/$vertical/': typeof VerticalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$vertical/$locationSlug' | '/$vertical/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$vertical/$locationSlug' | '/$vertical'
  id: '__root__' | '/' | '/$vertical/$locationSlug' | '/$vertical/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VerticalLocationSlugRoute: typeof VerticalLocationSlugRoute
  VerticalIndexRoute: typeof VerticalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$vertical/': {
      id: '/$vertical/'
      path: '/$vertical'
      fullPath: '/$vertical/'
      preLoaderRoute: typeof VerticalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$vertical/$locationSlug': {
      id: '/$vertical/$locationSlug'
      path: '/$vertical/$locationSlug'
      fullPath: '/$vertical/$locationSlug'
      preLoaderRoute: typeof VerticalLocationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VerticalLocationSlugRoute: VerticalLocationSlugRoute,
  VerticalIndexRoute: VerticalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
